spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/medcompare
spring.datasource.username=root
spring.datasource.password=5002ve21$ud52

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true