spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/medcompare
spring.datasource.username=root
spring.datasource.password=vedika@5002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vedikapatil710@gmail.com
spring.mail.password=dhmomdunpbvmmlhq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# App base URL
app.base-url=http://localhost:5501